# Generated by Django 3.1.5 on 2021-01-17 19:39

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter a course name', max_length=100, verbose_name='Название')),
                ('desc', models.TextField(help_text='Enter a description of the course', max_length=1000, verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='UsersStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('p', 'process'), ('f', 'finished')], max_length=1)),
                ('time', models.DateField()),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.course')),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('text', models.TextField(help_text='Enter a text of the cards', max_length=1000, verbose_name='Описание')),
                ('title', models.CharField(help_text='Enter a title of the cards', max_length=100, verbose_name='Заголовок')),
                ('queue', models.IntegerField(help_text='Enter the place of queue', verbose_name='Место в очереди')),
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Уникальный ID', primary_key=True, serialize=False)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.course')),
            ],
            options={
                'ordering': ['queue'],
            },
        ),
    ]
