# Generated by Django 3.1.5 on 2021-01-18 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20210118_1246'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Card',
        ),
    ]
