# Generated by Django 3.1.5 on 2021-01-18 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_delete_card'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введите заголовок карточки', max_length=100, verbose_name='Заголовок')),
                ('text', models.TextField(help_text='Введите контент карточки', max_length=1000, verbose_name='Контент карточки')),
                ('queue', models.IntegerField(help_text='Введите место в очереди', verbose_name='Место в очереди')),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.course')),
            ],
            options={
                'ordering': ['queue'],
            },
        ),
    ]
