# Generated by Django 3.1.5 on 2021-01-30 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_auto_20210123_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='img',
            field=models.TextField(default='null', help_text='Укажите путь к фотографии', max_length=100, verbose_name='Фотография'),
        ),
    ]
